/* ComicCraft Studio editor. The browser owns presentation and human edits; the local service owns persistence, layout and Codex image jobs. */
(() => {
  'use strict';
  const SVG_NS='http://www.w3.org/2000/svg',W=720,H=1000,LS_KEY='comiccraft-project-v2';
  const types={main:{label:'主格',icon:'▣',color:'#ff796c'},sub:{label:'副格',icon:'▤',color:'#6ba5ff'},base:{label:'底图',icon:'▧',color:'#9aa5ba'},gradient:{label:'渐变',icon:'◒',color:'#b080ff'},bubble:{label:'气泡',icon:'◯',color:'#60d7bd'}};
  const $=id=>document.getElementById(id),canvas=$('comicCanvas'),objectLayer=$('objectLayer'),selectionBox=$('selectionBox'),handles=$('selectionHandles');
  const state={episodes:[],assets:[],jobs:[],episodeId:'',pageId:'',selectedId:'',zoom:1,tool:'select',online:false,dragging:null,resizing:null,panning:null,inspectorId:'',history:[],future:[],editRecorded:false};
  const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`,clone=v=>window.structuredClone?structuredClone(v):JSON.parse(JSON.stringify(v));
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const safeColor=v=>/^#[0-9a-f]{6}$/i.test(v||'')?v:'#ffffff';
  const currentEpisode=()=>state.episodes.find(e=>e.id===state.episodeId)||state.episodes[0],currentPage=()=>currentEpisode()?.pages.find(p=>p.id===state.pageId)||currentEpisode()?.pages[0],selected=()=>currentPage()?.objects.find(o=>o.id===state.selectedId),svgEl=(n,a={})=>{const e=document.createElementNS(SVG_NS,n);Object.entries(a).forEach(([k,v])=>e.setAttribute(k,v));return e;};
  function defaultObjects(){return[
    {id:'base-1',type:'base',name:'底图 · 城市夜景',parentId:'main-1',x:61,y:70,w:598,h:510,rotation:0,opacity:1,visible:true,locked:false,src:'',assetId:'',fit:'cover'},
    {id:'base-2',type:'base',name:'底图 · 反应镜头',parentId:'sub-1',x:61,y:610,w:285,h:310,rotation:0,opacity:1,visible:true,locked:false,src:'',assetId:'',fit:'cover'},
    {id:'base-3',type:'base',name:'底图 · 细节镜头',parentId:'sub-2',x:374,y:610,w:285,h:310,rotation:0,opacity:1,visible:true,locked:false,src:'',assetId:'',fit:'cover'},
    {id:'main-1',type:'main',name:'主格 · 冲突',x:61,y:70,w:598,h:510,rotation:0,opacity:1,visible:true,locked:false,stroke:'#202433',strokeWidth:4,radius:3},
    {id:'sub-1',type:'sub',name:'副格 · 反应',x:61,y:610,w:285,h:310,rotation:0,opacity:1,visible:true,locked:false,stroke:'#202433',strokeWidth:4,radius:3},
    {id:'sub-2',type:'sub',name:'副格 · 细节',x:374,y:610,w:285,h:310,rotation:0,opacity:1,visible:true,locked:false,stroke:'#202433',strokeWidth:4,radius:3},
    {id:'gradient-1',type:'gradient',name:'渐变 · 氛围光',x:61,y:70,w:598,h:510,rotation:0,opacity:.23,visible:true,locked:false,startColor:'#ff7b67',endColor:'#6037b8',angle:45},
    {id:'bubble-1',type:'bubble',name:'气泡 · 台词 01',x:107,y:108,w:210,h:92,rotation:-4,opacity:1,visible:true,locked:false,fill:'#ffffff',text:'你终于来了。',fontFamily:'Microsoft YaHei',fontSize:20,tail:'left'},
    {id:'bubble-2',type:'bubble',name:'气泡 · 台词 02',x:420,y:700,w:185,h:87,rotation:3,opacity:1,visible:true,locked:false,fill:'#ffffff',text:'这次不会再逃了。',fontFamily:'Microsoft YaHei',fontSize:20,tail:'left'}
  ];}
  function defaultProject(){const p={id:'page-1',name:'第 1 页',revision:0,width:W,height:H,objects:defaultObjects(),assets:[],referenceIds:[],generation_standard:'',storyboard:{text:'',csv:''},layout_reference:''};return{episodes:[{id:'episode-1',title:'第一话',name:'第一话',pages:[p],assets:[],generation_standard:'',layout_reference_paths:[]}]};}
  function normalizeObject(o){const r={...o};r.id=r.id||uid(r.type||'object');r.type=r.type||'sub';r.name=r.name||types[r.type]?.label||'对象';r.x=Number(r.x||0);r.y=Number(r.y||0);r.w=Math.max(20,Number(r.w||100));r.h=Math.max(20,Number(r.h||100));r.rotation=Number(r.rotation||0);r.opacity=Math.max(0,Math.min(1,Number(r.opacity??1)));r.visible=r.visible!==false;r.locked=!!r.locked;return r;}
  function normalizeProject(input){const fallback=defaultProject();const source=Array.isArray(input)?{episodes:input}:input;const es=(source?.episodes||[]).map((e,ei)=>({id:e.id||`episode-${ei+1}`,title:e.title||e.name||`第${ei+1}话`,name:e.name||e.title||`第${ei+1}话`,assets:Array.isArray(e.assets)?e.assets:[],generation_standard:e.generation_standard||'',layout_reference_paths:e.layout_reference_paths||[],pages:(e.pages||[]).map((p,pi)=>({id:p.id||`${e.id||`episode-${ei+1}`}-page-${pi+1}`,name:p.name||`第 ${pi+1} 页`,revision:Number(p.revision||0),width:Number(p.width||W),height:Number(p.height||H),objects:(p.objects||[]).map(normalizeObject),assets:Array.isArray(p.assets)?p.assets:[],referenceIds:p.referenceIds||[],generation_standard:p.generation_standard||'',storyboard:p.storyboard||{text:'',csv:''},layout_reference:p.layout_reference||''}))}));return es.length?es:fallback.episodes;}
  function chooseInitialPage(){const ep=currentEpisode();if(!ep)return;if(!ep.pages.length)ep.pages.push({id:uid('page'),name:'第 1 页',revision:0,width:W,height:H,objects:defaultObjects(),assets:[],referenceIds:[],storyboard:{text:'',csv:''}});if(!state.pageId||!ep.pages.some(p=>p.id===state.pageId))state.pageId=ep.pages[0].id;if(!state.selectedId||!currentPage()?.objects.some(o=>o.id===state.selectedId))state.selectedId=currentPage()?.objects[0]?.id||'';}
  function renderLayerTree(){const tree=$('layerTree'),objects=currentPage()?.objects||[];tree.innerHTML=objects.slice().reverse().map(x=>`<div class="layer-row ${x.id===state.selectedId?'selected':''}" data-layer="${esc(x.id)}"><span class="layer-type" style="color:${types[x.type]?.color||'#9da5bb'}">${types[x.type]?.icon||'◈'}</span><span class="layer-name">${esc(x.name)}</span><button class="layer-visibility" data-toggle="${esc(x.id)}" title="切换显示">${x.visible?'●':'○'}</button><span class="layer-lock">${x.locked?'🔒':''}</span></div>`).join('');tree.querySelectorAll('[data-layer]').forEach(el=>el.onclick=()=>{state.selectedId=el.dataset.layer;state.inspectorId='';renderLayerTree();renderObjects();renderInspector(true);});tree.querySelectorAll('[data-toggle]').forEach(el=>el.onclick=ev=>{ev.stopPropagation();const x=objects.find(o=>o.id===el.dataset.toggle);if(!x)return;recordBeforeEdit();x.visible=!x.visible;currentPage().revision++;renderLayerTree();renderObjects();renderInspector(true);saveLocalDebounced();});}
  function render(){chooseInitialPage();renderSidebar();renderLayerTree();renderObjects();renderInspector();renderPageMeta();renderAssets();renderJobs();}
  function renderSidebar(){const ep=currentEpisode();$('episodeList').innerHTML=state.episodes.map(e=>`<div class="episode ${e.id===state.episodeId?'active':''}" data-episode="${esc(e.id)}"><span class="episode-icon">▤</span><span>${esc(e.title||e.name)}</span><span class="episode-meta">${e.pages.length}页</span></div>`).join('');$('pageList').innerHTML=(ep?.pages||[]).map(p=>`<div class="page ${p.id===state.pageId?'active':''}" data-page="${esc(p.id)}"><span class="page-thumb"></span><span>${esc(p.name)}</span></div>`).join('');document.querySelectorAll('[data-episode]').forEach(el=>el.onclick=()=>{state.episodeId=el.dataset.episode;state.pageId='';state.selectedId='';chooseInitialPage();render();});document.querySelectorAll('[data-page]').forEach(el=>el.onclick=()=>{state.pageId=el.dataset.page;state.selectedId='';chooseInitialPage();render();});}
  function ensureDefs(){const defs=canvas.querySelector('defs');defs.querySelectorAll('[data-dynamic]').forEach(e=>e.remove());const os=currentPage()?.objects||[];os.filter(o=>o.type==='main'||o.type==='sub').forEach(o=>{const c=svgEl('clipPath',{id:`clip-${o.id}`,'data-dynamic':'1'});c.append(svgEl('rect',{x:o.x,y:o.y,width:o.w,height:o.h,rx:o.radius||0}));defs.append(c);});os.filter(o=>o.type==='gradient').forEach(o=>{const id=`gradient-${o.id}`,g=svgEl('linearGradient',{id,'data-dynamic':'1'}),a=(Number(o.angle)||0)*Math.PI/180;g.setAttribute('x1',`${50-Math.cos(a)*50}%`);g.setAttribute('y1',`${50-Math.sin(a)*50}%`);g.setAttribute('x2',`${50+Math.cos(a)*50}%`);g.setAttribute('y2',`${50+Math.sin(a)*50}%`);g.append(svgEl('stop',{offset:'0%', 'stop-color':safeColor(o.startColor)}),svgEl('stop',{offset:'100%', 'stop-color':safeColor(o.endColor)}));defs.append(g);});}
  function renderObjects(){ensureDefs();objectLayer.innerHTML='';const os=currentPage()?.objects||[];os.forEach(o=>{if(!o.visible)return;const g=svgEl('g',{class:`object object-${o.type}`,'data-id':o.id,opacity:o.opacity,transform:`rotate(${o.rotation} ${o.x+o.w/2} ${o.y+o.h/2})`});let body;const frame=o.type==='main'||o.type==='sub';if(o.type==='base'){const parent=os.find(p=>p.id===o.parentId&&(p.type==='main'||p.type==='sub'));body=svgEl('g',{'clip-path':parent?`url(#clip-${parent.id})`:''});if(!o.src&&!o.assetUrl)body.append(svgEl('rect',{x:o.x,y:o.y,width:o.w,height:o.h,fill:'#cad3e0',opacity:.55}));else body.append(svgEl('image',{x:o.x,y:o.y,width:o.w,height:o.h,href:o.src||o.assetUrl,preserveAspectRatio:'xMidYMid slice'}));}else if(o.type==='gradient'){body=svgEl('rect',{x:o.x,y:o.y,width:o.w,height:o.h,rx:o.radius||0,fill:`url(#gradient-${o.id})`});}else if(o.type==='bubble'){const fill=safeColor(o.fill),tailX=o.tail==='right'?o.x+o.w-54:o.x+38;body=svgEl('g');body.append(svgEl('path',{d:`M ${tailX} ${o.y+o.h-2} Q ${tailX-18} ${o.y+o.h+22} ${tailX+19} ${o.y+o.h-10}`,fill,stroke:'#202433','stroke-width':2.5}),svgEl('rect',{x:o.x,y:o.y,width:o.w,height:o.h,rx:Math.min(40,o.radius||28),fill,stroke:'#202433','stroke-width':2.5,filter:'url(#bubbleShadow)'}));const t=svgEl('text',{x:o.x+o.w/2,y:o.y+o.h/2+Number(o.fontSize||20)/3,'text-anchor':'middle',fill:'#202433','font-size':o.fontSize||20,'font-family':o.fontFamily||'sans-serif'});String(o.text||'对白').split('\n').forEach((line,i)=>{const s=svgEl('tspan',{x:o.x+o.w/2,dy:i?'1.2em':0});s.textContent=line;t.append(s);});body.append(t);}else if(frame){body=svgEl('rect',{x:o.x,y:o.y,width:o.w,height:o.h,rx:o.radius||0,fill:'none',stroke:o.stroke||'#202433','stroke-width':o.strokeWidth||4});const t=svgEl('text',{x:o.x+12,y:o.y+24,fill:o.stroke||'#6b7183','font-size':14,'font-family':'sans-serif'});t.textContent=types[o.type].label;body.append(t);}else body=svgEl('rect',{x:o.x,y:o.y,width:o.w,height:o.h,fill:o.fill||'none'});g.append(body);g.addEventListener('pointerdown',onObjectPointerDown);objectLayer.append(g);});updateSelection();}
  function updateSelection(){const o=selected();if(!o||!o.visible){selectionBox.setAttribute('visibility','hidden');handles.setAttribute('visibility','hidden');return;}selectionBox.setAttribute('visibility','visible');selectionBox.setAttribute('x',o.x);selectionBox.setAttribute('y',o.y);selectionBox.setAttribute('width',o.w);selectionBox.setAttribute('height',o.h);selectionBox.setAttribute('transform',`rotate(${o.rotation} ${o.x+o.w/2} ${o.y+o.h/2})`);handles.setAttribute('visibility','visible');handles.setAttribute('transform',`rotate(${o.rotation} ${o.x+o.w/2} ${o.y+o.h/2})`);[['nw',o.x,o.y],['ne',o.x+o.w,o.y],['sw',o.x,o.y+o.h],['se',o.x+o.w,o.y+o.h]].forEach(([c,x,y])=>{const h=handles.querySelector(`.${c}`);h.setAttribute('x',x-5.5);h.setAttribute('y',y-5.5);});}
  function numberField(k,l,v,min=-9999,max=9999,step=1){return `<div class="field"><label>${l}</label><input data-prop="${k}" type="number" value="${esc(v)}" min="${min}" max="${max}" step="${step}"></div>`;}function colorField(k,l,v){return `<div class="field"><label>${l}</label><input data-prop="${k}" type="color" value="${safeColor(v)}"></div>`;}
  function renderInspector(force=false){const o=selected(),form=$('propertyForm');$('selectedObject').className=`selected-object ${o?'':'empty'}`;$('selectedObject').textContent=o?`${types[o.type]?.icon||'◈'}  ${o.name}`:'未选择对象';$('duplicateBtn').disabled=!o;$('deleteBtn').disabled=!o;$('regenerateBtn').disabled=!(o&&(o.type==='main'||o.type==='sub'||o.type==='base'));if(!o){state.inspectorId='';form.className='property-form empty-form';form.textContent='选择对象后编辑属性';return;}if(!force&&state.inspectorId===o.id&&form.querySelector('[data-prop]')){updateControlValues(o);return;}state.inspectorId=o.id;let html=`<div class="field full"><label>名称</label><input data-prop="name" type="text" value="${esc(o.name)}"></div>${numberField('x','X',o.x)}${numberField('y','Y',o.y)}${numberField('w','宽度',o.w,20,W)}${numberField('h','高度',o.h,20,H)}${numberField('rotation','旋转',o.rotation,-360,360)}${numberField('opacity','不透明度',o.opacity,0,1,.01)}<div class="field check-field"><label>状态</label><span><label><input data-prop="visible" type="checkbox" ${o.visible?'checked':''}> 显示</label><label><input data-prop="locked" type="checkbox" ${o.locked?'checked':''}> 锁定</label></span></div>`;if(o.type==='main'||o.type==='sub')html+=`${colorField('stroke','描边',o.stroke||'#202433')}${numberField('strokeWidth','描边宽度',o.strokeWidth||4,0,30)}${numberField('radius','圆角',o.radius||0,0,100)}`;if(o.type==='base'){const fs=(currentPage()?.objects||[]).filter(x=>x.type==='main'||x.type==='sub');html+=`<div class="field full"><label>父级框</label><select data-prop="parentId"><option value="">无裁切框</option>${fs.map(x=>`<option value="${esc(x.id)}" ${o.parentId===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><div class="field full"><label>资产</label><select data-prop="assetId"><option value="">未绑定</option>${state.assets.map(a=>`<option value="${esc(a.id)}" ${o.assetId===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select></div>`;}if(o.type==='gradient')html+=`${colorField('startColor','起始色',o.startColor)}${colorField('endColor','结束色',o.endColor)}${numberField('angle','角度',o.angle||0,-360,360)}`;if(o.type==='bubble')html+=`${colorField('fill','填充色',o.fill)}<div class="field full"><label>文字</label><textarea data-prop="text" rows="2">${esc(o.text)}</textarea></div><div class="field"><label>字体</label><input data-prop="fontFamily" type="text" value="${esc(o.fontFamily||'Microsoft YaHei')}"></div>${numberField('fontSize','字号',o.fontSize||20,8,120)}<div class="field"><label>尾巴</label><select data-prop="tail"><option value="left" ${o.tail==='left'?'selected':''}>左</option><option value="right" ${o.tail==='right'?'selected':''}>右</option></select></div>`;form.className='property-form';form.innerHTML=html;form.querySelectorAll('[data-prop]').forEach(el=>{el.addEventListener('focus',recordBeforeEdit,{once:true});el.addEventListener('input',onPropertyInput);el.addEventListener('change',onPropertyInput);});}
  function updateControlValues(o){$('propertyForm').querySelectorAll('[data-prop]').forEach(el=>{if(document.activeElement===el)return;const k=el.dataset.prop;if(el.type==='checkbox')el.checked=!!o[k];else el.value=o[k]??'';});}
  function onPropertyInput(ev){const o=selected();if(!o)return;recordBeforeEdit();const el=ev.currentTarget,k=el.dataset.prop;o[k]=el.type==='checkbox'?el.checked:['x','y','w','h','rotation','opacity','strokeWidth','radius','angle','fontSize'].includes(k)?Number(el.value):el.value;if(k==='w')o.w=Math.max(20,o.w);if(k==='h')o.h=Math.max(20,o.h);if(o.type==='base'&&k==='assetId')bindAssetToBase(o);currentPage().revision++;state.dirty=true;renderObjects();renderLayerTree();renderSidebar();renderPageMeta();saveLocalDebounced();}
  function bindAssetToBase(o){const a=state.assets.find(x=>x.id===o.assetId);o.src=a?.url||a?.data_url||'';o.assetUrl=a?.url||'';o.assetPath=a?.path||'';}
  function renderPageMeta(){const e=currentEpisode(),p=currentPage();$('crumb').textContent=e?`${esc(e.title||e.name)} / ${esc(p?.name||'')}`:'';$('selectionHint').textContent=selected()?`${types[selected().type]?.label||'对象'} · ${selected().name}`:'选择一个对象开始编辑';if(document.activeElement!==$('storyboardText'))$('storyboardText').value=p?.storyboard?.text||'';if(document.activeElement!==$('storyboardCsv'))$('storyboardCsv').value=p?.storyboard?.csv||'';if(document.activeElement!==$('generationStandard'))$('generationStandard').value=p?.generation_standard||e?.generation_standard||'';if(document.activeElement!==$('layoutReference'))$('layoutReference').value=p?.layout_reference||'';}
  function renderAssets(){const list=$('assetList');if(!list)return;list.innerHTML=state.assets.length?state.assets.map(a=>`<button class="asset-row" data-asset="${esc(a.id)}"><span class="asset-thumb">${a.url?`<img src="${esc(a.url)}" alt="">`:'▧'}</span><span>${esc(a.name)}</span></button>`).join(''):'<div class="empty-note">还没有资产图</div>';list.querySelectorAll('[data-asset]').forEach(el=>el.onclick=()=>{const o=selected(),a=state.assets.find(x=>x.id===el.dataset.asset);if(o?.type==='base'&&a){recordBeforeEdit();o.assetId=a.id;bindAssetToBase(o);renderObjects();renderInspector(true);showToast(`已绑定资产：${a.name}`);}else showToast('请先选择底图对象');});}
  function pointerToSvg(ev){const pt=canvas.createSVGPoint();pt.x=ev.clientX;pt.y=ev.clientY;return pt.matrixTransform(canvas.getScreenCTM().inverse());}
  function onObjectPointerDown(ev){if(state.tool!=='select')return;ev.stopPropagation();const o=currentPage()?.objects.find(x=>x.id===ev.currentTarget.dataset.id);if(!o||o.locked)return;state.selectedId=o.id;state.inspectorId='';recordBeforeEdit();state.dragging={start:pointerToSvg(ev),x:o.x,y:o.y};canvas.setPointerCapture?.(ev.pointerId);renderObjects();renderInspector(true);}
  function rotateDelta(dx,dy,a){const r=a*Math.PI/180;return{x:dx*Math.cos(r)+dy*Math.sin(r),y:-dx*Math.sin(r)+dy*Math.cos(r)};}
  handles.querySelectorAll('.handle').forEach(handle=>handle.addEventListener('pointerdown',ev=>{ev.stopPropagation();const o=selected();if(!o||o.locked)return;recordBeforeEdit();state.resizing={corner:[...handle.classList].find(c=>['nw','ne','sw','se'].includes(c)),start:pointerToSvg(ev),x:o.x,y:o.y,w:o.w,h:o.h};canvas.setPointerCapture?.(ev.pointerId);}));
  canvas.addEventListener('pointermove',ev=>{const o=selected();if(!o)return;const p=pointerToSvg(ev);if(state.resizing){const r=state.resizing,d=rotateDelta(p.x-r.start.x,p.y-r.start.y,o.rotation),minW=20,minH=20;let sx=0,sy=0;if(r.corner.includes('e'))o.w=Math.max(minW,Math.round(r.w+d.x));if(r.corner.includes('s'))o.h=Math.max(minH,Math.round(r.h+d.y));if(r.corner.includes('w')){o.w=Math.max(minW,Math.round(r.w-d.x));sx=d.x;}if(r.corner.includes('n')){o.h=Math.max(minH,Math.round(r.h-d.y));sy=d.y;}const b=rotateDelta(sx,sy,-o.rotation);o.x=Math.round(r.x+b.x);o.y=Math.round(r.y+b.y);renderObjects();renderPageMeta();return;}if(!state.dragging)return;o.x=Math.round(state.dragging.x+p.x-state.dragging.start.x);o.y=Math.round(state.dragging.y+p.y-state.dragging.start.y);renderObjects();renderPageMeta();});canvas.addEventListener('pointerup',()=>{if(state.dragging||state.resizing){state.dragging=null;state.resizing=null;currentPage().revision++;state.dirty=true;saveLocalDebounced();showToast('对象已更新');}});canvas.addEventListener('pointerdown',()=>{if(state.tool==='select'){state.selectedId='';state.inspectorId='';render();}});
  const stage=$('canvasWrap');stage.addEventListener('pointerdown',ev=>{if(state.tool!=='pan')return;state.panning={x:ev.clientX,y:ev.clientY,left:stage.scrollLeft,top:stage.scrollTop};stage.setPointerCapture?.(ev.pointerId);});stage.addEventListener('pointermove',ev=>{if(state.panning){stage.scrollLeft=state.panning.left-(ev.clientX-state.panning.x);stage.scrollTop=state.panning.top-(ev.clientY-state.panning.y);}});stage.addEventListener('pointerup',()=>state.panning=null);
  function recordBeforeEdit(){if(state.editRecorded)return;state.history.push(clone(state.episodes));if(state.history.length>50)state.history.shift();state.future=[];state.editRecorded=true;setTimeout(()=>state.editRecorded=false,0);}function undo(){if(!state.history.length)return;state.future.push(clone(state.episodes));state.episodes=state.history.pop();chooseInitialPage();render();saveLocalDebounced();}function redo(){if(!state.future.length)return;state.history.push(clone(state.episodes));state.episodes=state.future.pop();chooseInitialPage();render();saveLocalDebounced();}
  function deleteSelected(){const p=currentPage(),o=selected();if(!p||!o)return;recordBeforeEdit();p.objects=p.objects.filter(x=>x.id!==o.id);state.selectedId=p.objects.at(-1)?.id||'';state.inspectorId='';render();saveLocalDebounced();showToast('对象已删除');}function moveLayer(delta){const p=currentPage(),i=p?.objects.findIndex(o=>o.id===state.selectedId);if(!p||i<0||i+delta<0||i+delta>=p.objects.length)return;recordBeforeEdit();const[o]=p.objects.splice(i,1);p.objects.splice(i+delta,0,o);renderObjects();renderInspector(true);}
  $('undoBtn').onclick=undo;$('redoBtn').onclick=redo;document.addEventListener('keydown',ev=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)){return;}const o=selected();if(ev.key==='Delete'&&o&&!o.locked){ev.preventDefault();deleteSelected();}if(o&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(ev.key)&&!o.locked){ev.preventDefault();recordBeforeEdit();const s=ev.shiftKey?10:1;if(ev.key==='ArrowLeft')o.x-=s;if(ev.key==='ArrowRight')o.x+=s;if(ev.key==='ArrowUp')o.y-=s;if(ev.key==='ArrowDown')o.y+=s;currentPage().revision++;renderObjects();renderPageMeta();saveLocalDebounced();}if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='z'){ev.preventDefault();ev.shiftKey?redo():undo();}if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='y'){ev.preventDefault();redo();}});
  $('duplicateBtn').onclick=()=>{const o=selected();if(!o)return;recordBeforeEdit();const c={...clone(o),id:uid(o.type),name:`${o.name} · 副本`,x:o.x+18,y:o.y+18};currentPage().objects.push(c);state.selectedId=c.id;render();saveLocalDebounced();};$('deleteBtn').onclick=deleteSelected;$('moveUpBtn')?.addEventListener('click',()=>moveLayer(1));$('moveDownBtn')?.addEventListener('click',()=>moveLayer(-1));
  $('addObjectBtn').onclick=()=>{if(document.querySelector('.object-menu'))return;const menu=document.createElement('div');menu.className='object-menu';Object.entries(types).forEach(([type,m])=>{const b=document.createElement('button');b.className='object-option';b.innerHTML=`<span class="option-icon" style="color:${m.color}">${m.icon}</span><span>${m.label}</span>`;b.onclick=()=>{recordBeforeEdit();const o=normalizeObject({id:uid(type),type,name:`${m.label} · 新对象`,x:110,y:140,w:type==='bubble'?220:240,h:type==='bubble'?90:180,fill:'#ffffff',startColor:'#ff7b67',endColor:'#6037b8',angle:45,text:'新对白',fontFamily:'Microsoft YaHei',fontSize:20,tail:'left',stroke:'#202433',strokeWidth:4,radius:type==='bubble'?28:3});currentPage().objects.push(o);state.selectedId=o.id;menu.remove();render();saveLocalDebounced();};menu.appendChild(b);});document.body.append(menu);const close=ev=>{if(!menu.contains(ev.target)&&ev.target!==$('addObjectBtn')){menu.remove();document.removeEventListener('pointerdown',close);}};document.addEventListener('pointerdown',close);};
  $('newEpisodeBtn').onclick=()=>{recordBeforeEdit();const n=state.episodes.length+1,p={id:uid('page'),name:'第 1 页',revision:0,width:W,height:H,objects:defaultObjects(),assets:[],referenceIds:[],storyboard:{text:'',csv:''}},e={id:uid('episode'),title:`第${n}话`,name:`第${n}话`,pages:[p],assets:[],generation_standard:'',layout_reference_paths:[]};state.episodes.push(e);state.episodeId=e.id;state.pageId=p.id;state.selectedId='main-1';render();saveLocalDebounced();};$('newPageBtn').onclick=()=>{recordBeforeEdit();const e=currentEpisode(),p={id:uid('page'),name:`第 ${e.pages.length+1} 页`,revision:0,width:W,height:H,objects:defaultObjects(),assets:[],referenceIds:[],storyboard:{text:'',csv:''}};e.pages.push(p);state.pageId=p.id;state.selectedId='main-1';render();saveLocalDebounced();};
  function setZoom(v){state.zoom=Math.max(.5,Math.min(1.5,v));canvas.style.transform=`scale(${state.zoom})`;$('zoomValue').textContent=`${Math.round(state.zoom*100)}%`;}$('zoomIn').onclick=()=>setZoom(state.zoom+.1);$('zoomOut').onclick=()=>setZoom(state.zoom-.1);document.querySelector('[data-tool="select"]').onclick=()=>{state.tool='select';setToolButtons();};document.querySelector('[data-tool="pan"]').onclick=()=>{state.tool='pan';setToolButtons();};function setToolButtons(){document.querySelectorAll('.tool-btn[data-tool]').forEach(x=>x.classList.toggle('active',x.dataset.tool===state.tool));}
  async function api(path,opt={}){const r=await fetch(path,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let b={};try{b=await r.json();}catch{}if(!r.ok)throw new Error(b.error||`服务返回 ${r.status}`);return b;}
  async function checkHealth(){try{const h=await api('/api/health');state.online=!!h.ok;$('connectionText').textContent=state.online?'Codex 服务已连接':'本地离线（可保存）';$('connectionText').previousElementSibling.style.background=state.online?'var(--accent-2)':'#e4a34b';}catch{state.online=false;$('connectionText').textContent='本地离线（可保存）';$('connectionText').previousElementSibling.style.background='#e4a34b';}}
  async function loadProject(){try{const d=await api('/api/project');if(d.episodes)state.episodes=normalizeProject(d.episodes);}catch{const s=localStorage.getItem(LS_KEY);state.episodes=normalizeProject(s?JSON.parse(s):null);}state.episodeId=state.episodes[0]?.id||'';state.pageId=state.episodes[0]?.pages[0]?.id||'';chooseInitialPage();}
  async function loadAssets(){try{const d=await api('/api/assets');state.assets=Array.isArray(d.assets)?d.assets:[];}catch{state.assets=[];}}
  function mergePageAssets(){state.episodes.flatMap(e=>e.pages||[]).forEach(p=>(p.assets||[]).forEach(a=>{if(a.id&&!state.assets.some(x=>x.id===a.id))state.assets.push({...a,name:a.name||a.id,url:a.url||a.data_url||''});}));}
  async function loadJobs(){try{const d=await api('/api/jobs');const list=Array.isArray(d)?d:(d.jobs||[]);state.jobs=list.map(j=>({...j,id:j.id||j.job_id,remoteId:j.id||j.job_id,targetName:j.targetName||j.target_name||'已提交任务'})).filter(j=>j.id);list.filter(j=>j.status==='queued'||j.status==='running').forEach(remote=>{const j=state.jobs.find(x=>x.remoteId===(remote.id||remote.job_id));if(j)pollJob(j);});}catch{state.jobs=[];}}
  async function saveProject(){const payload={episodes:state.episodes};localStorage.setItem(LS_KEY,JSON.stringify(payload));try{await api('/api/project',{method:'PUT',body:JSON.stringify(payload)});$('saveState').textContent='已保存到项目';}catch{$('saveState').textContent='已保存到本机（离线）';}state.dirty=false;showToast('项目已保存');}
  let saveTimer;function saveLocalDebounced(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>localStorage.setItem(LS_KEY,JSON.stringify({episodes:state.episodes})),500);}$('saveBtn').onclick=saveProject;
  $('exportProjectBtn').onclick=()=>{const blob=new Blob([JSON.stringify({episodes:state.episodes},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='project.json';a.click();URL.revokeObjectURL(url);showToast('已导出 project.json');};
  $('loadProjectBtn').onclick=()=>$('projectFile').click();$('projectFile').onchange=ev=>{const file=ev.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(String(reader.result));recordBeforeEdit();state.episodes=normalizeProject(parsed);state.episodeId=state.episodes[0]?.id||'';state.pageId=state.episodes[0]?.pages[0]?.id||'';state.selectedId='';chooseInitialPage();mergePageAssets();render();saveLocalDebounced();showToast('project.json 已载入');}catch{showToast('载入失败：不是有效的 project.json');}};reader.readAsText(file);ev.target.value='';};
  ['storyboardText','storyboardCsv','generationStandard','layoutReference'].forEach(id=>$(id).addEventListener('input',ev=>{const p=currentPage(),e=currentEpisode();if(!p)return;recordBeforeEdit();if(id==='storyboardText'){p.storyboard=p.storyboard||{};p.storyboard.text=ev.target.value;}else if(id==='storyboardCsv'){p.storyboard=p.storyboard||{};p.storyboard.csv=ev.target.value;}else if(id==='generationStandard')p.generation_standard=ev.target.value;else p.layout_reference=ev.target.value;p.revision++;saveLocalDebounced();}));
  $('uploadAssetBtn').onclick=()=>$('assetFile').click();$('assetFile').onchange=async ev=>{const file=ev.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=async()=>{const dataUrl=String(reader.result);let a={id:uid('asset'),name:file.name,url:dataUrl,data_url:dataUrl,path:''};try{a={...a,...await api('/api/assets',{method:'POST',body:JSON.stringify({name:file.name,data_url:dataUrl})})};a.url=a.url||dataUrl;}catch{}state.assets.push(a);const p=currentPage();p.assets=p.assets||[];p.assets.push({id:a.id,name:a.name,url:a.url,path:a.path||''});const o=selected();if(o?.type==='base'){recordBeforeEdit();o.assetId=a.id;bindAssetToBase(o);}render();saveLocalDebounced();showToast(`已加入资产：${file.name}`);};reader.readAsDataURL(file);ev.target.value='';};
  function renderJobs(){const box=$('jobQueue');box.innerHTML=state.jobs.slice(0,6).map(j=>`<div class="job"><div class="job-head"><span>${esc(j.targetName||'当前页面')}</span><span class="job-status ${j.status==='failed'?'error':j.needsApply?'waiting':j.status==='succeeded'?'done':''}">${esc(j.needsApply?'已完成 · 等待应用':j.phase||j.status||'排队中')}</span></div>${j.error?`<div class="job-error">${esc(j.error)}</div>`:''}${j.needsApply?`<button class="small-btn apply-job" data-apply-job="${esc(j.id)}">应用结果</button>`:''}</div>`).join('');box.querySelectorAll('[data-apply-job]').forEach(el=>el.onclick=()=>{const j=state.jobs.find(x=>x.id===el.dataset.applyJob);if(j?.remote)applyRemoteResult(j,j.remote,true);});}
  function addJob(j){state.jobs.unshift(j);if(state.jobs.length>12)state.jobs.length=12;renderJobs();}
  $('queueBtn').onclick=queuePipeline;async function queuePipeline(){const e=currentEpisode(),p=currentPage();if(!e||!p)return;const j={id:uid('job'),targetEpisodeId:e.id,targetPageId:p.id,targetName:`${e.title||e.name} / ${p.name}`,expectedRevision:p.revision,status:'queued',phase:'提交中'};addJob(j);const snapshot=clone(p);try{const r=await api('/api/jobs',{method:'POST',body:JSON.stringify({kind:'pipeline',payload:{episode:e,page:snapshot,assets:(p.assets||[]).map(a=>a.path||a.url).filter(Boolean),reference_ids:p.referenceIds||[],generation_standard:p.generation_standard||e.generation_standard||''},expected_revision:p.revision})});j.remoteId=r.id||r.job_id;j.status=r.status||'queued';j.phase=r.phase||'排队中';renderJobs();pollJob(j);}catch(err){j.status='failed';j.phase='提交失败';j.error=err.message;renderJobs();}}
  $('regenerateBtn').onclick=async()=>{const o=selected(),p=currentPage();if(!o||!p)return;const j={id:uid('job'),targetEpisodeId:currentEpisode().id,targetPageId:p.id,targetName:`${currentEpisode().title||currentEpisode().name} / ${p.name} · 单格`,expectedRevision:p.revision,status:'queued',phase:'提交单格生图'};addJob(j);try{const r=await api('/api/jobs',{method:'POST',body:JSON.stringify({kind:'image',payload:{panel_id:o.type==='base'?(o.parentId||o.id):o.id,prompt:$('layoutPrompt').value,asset_paths:(p.assets||[]).map(a=>a.path).filter(Boolean)},expected_revision:p.revision})});j.remoteId=r.id||r.job_id;pollJob(j);}catch(err){j.status='failed';j.phase='提交失败';j.error=err.message;renderJobs();}};
  async function pollJob(j){if(!j.remoteId)return;try{const r=await api(`/api/jobs/${encodeURIComponent(j.remoteId)}`);j.remote=r;j.status=r.status||j.status;j.phase=r.phase||j.phase;if(['succeeded','completed','done'].includes(r.status)){const target=state.episodes.flatMap(e=>e.pages||[]).find(p=>p.id===j.targetPageId);if(target&&target.revision===j.expectedRevision)applyRemoteResult(j,r,false);else{j.needsApply=true;j.phase='已完成 · 页面已被人工修改';renderJobs();}}else if(r.status==='failed'){j.phase='失败';j.error=r.error||'任务失败';renderJobs();}else{renderJobs();setTimeout(()=>pollJob(j),1000);}}catch(err){j.status='failed';j.phase='读取状态失败';j.error=err.message;renderJobs();}}
  function applyRemoteResult(j,r,force){const p=state.episodes.flatMap(e=>e.pages).find(x=>x.id===j.targetPageId);if(!p)return;if(!force&&p.revision!==j.expectedRevision){j.needsApply=true;j.phase='已完成 · 等待应用';renderJobs();return;}const result=r.result||{},layout=result.layout||{};if(Array.isArray(layout.objects)&&layout.objects.length)p.objects=layout.objects.map(normalizeObject);(Array.isArray(result.images)?result.images:[]).forEach(img=>{const id=img.panel_id||img.panelId,a=img.artifact||{};let b=p.objects.find(o=>o.type==='base'&&(o.parentId===id||o.id===id));if(!b){b=normalizeObject({id:`${id}-base`,type:'base',name:`${id} · 生成图`,parentId:id,x:0,y:0,w:W,h:H,visible:true,locked:false});p.objects.unshift(b);}b.src=a.url||a.path||'';b.assetUrl=a.url||'';b.assetPath=a.path||'';b.generatedArtifactId=a.id||'';});p.revision++;j.needsApply=false;j.phase='已应用';j.status='succeeded';render();saveLocalDebounced();showToast('Codex 结果已应用');}
  $('exportBtn').onclick=()=>{const s=canvas.cloneNode(true);s.querySelector('#selectionBox')?.setAttribute('visibility','hidden');s.querySelector('#selectionHandles')?.setAttribute('visibility','hidden');s.setAttribute('width',W);s.setAttribute('height',H);const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(s)],{type:'image/svg+xml;charset=utf-8'})),img=new Image();img.onload=()=>{const out=document.createElement('canvas');out.width=W;out.height=H;out.getContext('2d').drawImage(img,0,0,W,H);out.toBlob(b=>{if(!b)return;const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`${currentEpisode().title||'episode'}-${currentPage().name}.png`;a.click();URL.revokeObjectURL(url);showToast('已导出 PNG');},'image/png');};img.onerror=()=>{URL.revokeObjectURL(url);showToast('导出失败：图片资源不可用');};img.src=url;};
  function showToast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2200);}
  async function boot(){const s=localStorage.getItem(LS_KEY);state.episodes=normalizeProject(s?JSON.parse(s):null);state.episodeId=state.episodes[0]?.id||'';state.pageId=state.episodes[0]?.pages[0]?.id||'';chooseInitialPage();await Promise.all([checkHealth(),loadAssets(),loadJobs()]);mergePageAssets();try{const d=await api('/api/project');if(d.episodes){state.episodes=normalizeProject(d.episodes);state.episodeId=state.episodes[0]?.id||'';state.pageId=state.episodes[0]?.pages[0]?.id||'';chooseInitialPage();mergePageAssets();}}catch{}render();}
  boot();
})();



